# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               fawx
tagline:             'by Erik Frey'
description:         "Personal website of Erik Frey.  Established 2003, frequently neglected, here to stay."
url:                 http://fawx.com
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Erik Frey
  email:             misc@fawx.com

# Custom vars
version:             1.0.0
